export enum FieldName {
  merchantIdScanReference = 'merchantIdScanReference',
  frontsideImage = 'frontsideImage',
  faceImage = 'faceImage',
  country = 'country',
  idType = 'idType',
  frontsideImageMimeType = 'frontsideImageMimeType',
  faceImageMimeType = 'faceImageMimeType',
  backsideImage = 'backsideImage',
  backsideImageMimeType = 'backsideImageMimeType',
  enabledFields = 'enabledFields',
  merchantReportingCriteria = 'merchantReportingCriteria',
  customerId = 'customerId',
  callbackUrl = 'callbackUrl',
  firstName = 'firstName',
  lastName = 'lastName',
  usState = 'usState',
  expiry = 'expiry',
  number = 'number',
  dob = 'dob',
  callbackGranularity = 'callbackGranularity',
  personalNumber = 'personalNumber'
}
